const fs = require('fs');
const archiver = require('archiver');

function createZip(sourceDir, destZipPath) {
  return new Promise((resolve, reject) => {
    const output = fs.createWriteStream(destZipPath);
    const archive = archiver('zip', { zlib: { level: 9 } });
    output.on('close', () => resolve(archive.pointer()));
    output.on('error', reject);
    archive.on('error', reject);
    archive.pipe(output);
    archive.directory(sourceDir, false);
    archive.finalize();
  });
}

// Generates a self-contained, self-deleting PHP script: verifies a shared
// secret (timing-safe), wipes the target directory, extracts the uploaded
// zip into it, then deletes both the zip and itself regardless of outcome.
// The target directory is baked in at generation time (not request input),
// so a leaked secret can only ever trigger a re-extraction of this exact zip
// into this exact, pre-decided path — not an arbitrary path traversal.
function renderExtractorScript({ secret, targetRelative, zipName }) {
  const phpSecret = JSON.stringify(secret);
  const phpTarget = JSON.stringify(targetRelative);
  const phpZip = JSON.stringify(zipName);

  return `<?php
// Auto-generated by ftp-pusher. Deletes itself (and the zip) after one run.
$secret = ${phpSecret};
$targetRelative = ${phpTarget};
$zipFile = __DIR__ . '/' . ${phpZip};

header('Content-Type: application/json');

function ftp_pusher_respond($ok, $message) {
    global $zipFile;
    echo json_encode(['ok' => $ok, 'message' => $message]);
    if (file_exists($zipFile)) { @unlink($zipFile); }
    @unlink(__FILE__);
    exit;
}

$input = json_decode(file_get_contents('php://input'), true);
$provided = is_array($input) && isset($input['secret'])
    ? $input['secret']
    : ($_POST['secret'] ?? $_GET['secret'] ?? '');

if (!hash_equals($secret, (string) $provided)) {
    http_response_code(403);
    ftp_pusher_respond(false, 'invalid secret');
}

if (!file_exists($zipFile)) {
    http_response_code(404);
    ftp_pusher_respond(false, 'zip not found');
}

function ftp_pusher_rrmdir($dir) {
    if (!is_dir($dir)) return;
    foreach (scandir($dir) as $item) {
        if ($item === '.' || $item === '..') continue;
        $path = $dir . '/' . $item;
        is_dir($path) ? ftp_pusher_rrmdir($path) : @unlink($path);
    }
    @rmdir($dir);
}

$target = __DIR__ . '/' . $targetRelative;
ftp_pusher_rrmdir($target);
@mkdir($target, 0755, true);

$zip = new ZipArchive();
if ($zip->open($zipFile) !== true) {
    http_response_code(500);
    ftp_pusher_respond(false, 'failed to open zip');
}
$zip->extractTo($target);
$zip->close();

ftp_pusher_respond(true, 'extracted');
`;
}

async function triggerExtraction(url, secret) {
  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ secret })
  });
  const text = await res.text();
  let parsed = null;
  try {
    parsed = JSON.parse(text);
  } catch {
    // fall through with parsed === null; raw text used in the error below
  }
  if (!res.ok || !parsed || parsed.ok !== true) {
    const detail = parsed && parsed.message ? parsed.message : text.slice(0, 200);
    throw new Error(`Extraction endpoint failed (HTTP ${res.status}): ${detail}`);
  }
  return parsed;
}

module.exports = { createZip, renderExtractorScript, triggerExtraction };
